import { UserRoleProfile, Vehicle, ServiceTicket, Technician, VendorFleetVehicle, RolePermissionConfig } from './types';

export const initialProfiles: Record<string, UserRoleProfile> = {
  CEO: {
    id: 'usr_ceo_001',
    name: 'Sri Hari Kolusu',
    email: 'ceo@innovibemobility.com',
    role: 'CEO',
    title: 'Founder & CEO (Admin)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    permissions: ['ALL_ACCESS', 'MANAGE_ROLES', 'VIEW_REVENUE', 'SYSTEM_GOVERNANCE'],
  },
  COO: {
    id: 'usr_coo_002',
    name: 'Rajesh Varma',
    email: 'coo@innovibemobility.com',
    role: 'COO',
    title: 'Chief Operating Officer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    permissions: ['VIEW_OPERATIONS', 'DISPATCH_MANAGEMENT', 'FLEET_SYNC', 'VENDOR_ACCESS'],
  },
  CTO: {
    id: 'usr_cto_003',
    name: 'Ananya Sharma',
    email: 'cto@innovibemobility.com',
    role: 'CTO',
    title: 'Chief Technology Officer',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    permissions: ['TELEMETRY_VIEW', 'AI_AGENTS_CONFIG', 'SYSTEM_LOGS', 'SECURITY_AUDIT'],
  },
  SERVICE_MANAGER: {
    id: 'usr_sm_004',
    name: 'Vikram Singh',
    email: 'sm.kakinada@innovibemobility.com',
    role: 'SERVICE_MANAGER',
    title: 'Kakinada Service Hub Manager',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    permissions: ['TICKETS_MANAGE', 'QUOTATIONS_APPROVE', 'TECHNICIAN_ASSIGN'],
  },
  HR: {
    id: 'usr_hr_005',
    name: 'Pooja Reddy',
    email: 'hr@innovibemobility.com',
    role: 'HR',
    title: 'Head of Human Resources',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250',
    permissions: ['STAFF_MANAGEMENT', 'PRODUCTIVITY_ANALYTICS', 'ATTENDANCE_ROSTER'],
  },
  TECHNICIAN: {
    id: 'usr_tech_006',
    name: 'Rahul Sharma',
    email: 'tech@innovibemobility.com',
    role: 'TECHNICIAN',
    title: 'Senior EV Technician',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    permissions: ['VIEW_JOB_CARDS', 'UPDATE_TICKETS', 'VIEW_SOP'],
  },
  EMPLOYEE: {
    id: 'usr_emp_007',
    name: 'Sneha Patel',
    email: 'employee@innovibemobility.com',
    role: 'EMPLOYEE',
    title: 'Operations Specialist (Employee)',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
    permissions: ['VIEW_TASKS', 'SUBMIT_ATTENDANCE', 'VIEW_BENEFITS', 'LOG_TICKETS'],
  },
};

export const defaultRoleConfigs: RolePermissionConfig[] = [
  {
    role: 'CEO',
    roleName: 'CEO Dashboard (Super Admin)',
    description: 'Full system control, administrative governance, revenue monitoring, role creation & access management.',
    accessibleFeatures: ['Super Admin Suite', 'Role & Permission Manager', 'P&L Financials', 'AI Back-Office Metrics'],
  },
  {
    role: 'COO',
    roleName: 'COO Dashboard (Operations & Logistics)',
    description: 'Real-time dispatch matrix, service ticket bottlenecks, vendor EV fleet integration data.',
    accessibleFeatures: ['Live Dispatch Map', 'Vendor Fleet Dashboard Sync', 'Service Center Bottlenecks', 'RSA Operations'],
  },
  {
    role: 'CTO',
    roleName: 'CTO Dashboard (AI & Telematics)',
    description: 'EV Health Score 0-100 monitoring engine, AI microservices health (n8n/Ollama), infrastructure logs.',
    accessibleFeatures: ['EV Health Telematics', 'AI Agent Pipeline', 'Telescope API Latency', 'Quantum-Safe Security'],
  },
  {
    role: 'SERVICE_MANAGER',
    roleName: 'Service Manager Dashboard',
    description: 'Incoming ticket queue, AI Service Advisor diagnoses, AI Dispatcher recommendations, quotation approval.',
    accessibleFeatures: ['Ticket Management Queue', 'AI Service Advisor', 'AI Dispatcher Recommendation', 'Quote Workbench'],
  },
  {
    role: 'HR',
    roleName: 'HR Dashboard (Human Resources)',
    description: 'Technician productivity stats, customer rating reviews, SLA compliance, staff attendance rosters.',
    accessibleFeatures: ['Technician Performance Index', 'Customer Feedback Audits', 'Staff Attendance Roster', 'SLA Analytics'],
  },
  {
    role: 'TECHNICIAN',
    roleName: 'Technician Portal',
    description: 'Assigned job cards, SOPs, and service execution workflows.',
    accessibleFeatures: ['Job Cards', 'SOPs', 'Parts Requisition', 'Service Reports'],
  },
  {
    role: 'EMPLOYEE',
    roleName: 'Employee Portal (Staff Workspace)',
    description: 'Employee personal dashboard, daily task queue, timesheets, and internal workplace requests.',
    accessibleFeatures: ['Employee Workspace', 'Daily Tasks & SOP', 'Attendance & Leaves', 'Internal Helpdesk'],
  },
];

// Mapped exactly to Laravel `vehicles` and `brands` database seeders
export const mockVehicles: Vehicle[] = [
  {
    id: 'veh_001',
    vin: 'INNO450X2026001',
    registrationNumber: 'AP39AB1234',
    make: 'Ather Energy',
    model: 'Ather 450X Apex',
    year: 2024,
    ownerName: 'User 1',
    ownerMobile: '+91 9000000001',
    healthScore: {
      overall: 94,
      batteryHealth: 96,
      motorEfficiency: 98,
      controllerTemp: 42,
      brakeWear: 88,
      tyreCondition: 92,
      lastUpdated: '2 mins ago',
      status: 'OPTIMAL',
    },
    lastServiceDate: '15 Jan 2026',
    nextServiceDue: '15 Jul 2026',
  },
  {
    id: 'veh_002',
    vin: 'INNOOLA02026002',
    registrationNumber: 'AP39CD5678',
    make: 'Ola Electric',
    model: 'Ola S1 Pro Gen2',
    year: 2023,
    ownerName: 'User 2',
    ownerMobile: '+91 9000000002',
    healthScore: {
      overall: 78,
      batteryHealth: 82,
      motorEfficiency: 85,
      controllerTemp: 56,
      brakeWear: 64,
      tyreCondition: 70,
      lastUpdated: '5 mins ago',
      status: 'ATTENTION',
    },
    lastServiceDate: '10 Oct 2025',
    nextServiceDue: '10 Apr 2026',
  },
  {
    id: 'veh_003',
    vin: 'INNOTVS02026003',
    registrationNumber: 'AP39EF9012',
    make: 'TVS Motor',
    model: 'iQube ST',
    year: 2024,
    ownerName: 'User 3',
    ownerMobile: '+91 9000000003',
    healthScore: {
      overall: 52,
      batteryHealth: 60,
      motorEfficiency: 70,
      controllerTemp: 68,
      brakeWear: 40,
      tyreCondition: 45,
      lastUpdated: '1 min ago',
      status: 'CRITICAL',
    },
    lastServiceDate: '01 Aug 2025',
    nextServiceDue: 'OVERDUE',
  },
  {
    id: 'veh_004',
    vin: 'INNOHERO02026004',
    registrationNumber: 'AP39GH3456',
    make: 'Hero Electric',
    model: 'Hero Electric Nyx',
    year: 2023,
    ownerName: 'User 4',
    ownerMobile: '+91 9000000004',
    healthScore: {
      overall: 89,
      batteryHealth: 91,
      motorEfficiency: 92,
      controllerTemp: 44,
      brakeWear: 84,
      tyreCondition: 88,
      lastUpdated: 'Just now',
      status: 'OPTIMAL',
    },
    lastServiceDate: '20 Feb 2026',
    nextServiceDue: '20 Aug 2026',
  },
];

// Mapped to Laravel `bookings` and `services` database seeders (Service prices: ₹199, ₹249, ₹499)
export const mockServiceTickets: ServiceTicket[] = [
  {
    id: 'tkt_101',
    ticketNumber: 'BK-2026-0001',
    customerName: 'User 1',
    customerPhone: '+91 9000000001',
    vehicleModel: 'Ather 450X Apex',
    registrationNumber: 'AP39AB1234',
    serviceType: 'Service at Home',
    status: 'IN_PROGRESS',
    aiSuggestedFault: 'Doorstep Periodic Service & Brake Caliper Adjustment',
    aiEstimatedCost: 249,
    aiEstimatedTimeMins: 45,
    location: 'Srinivasa Nagar, Hub 1',
    createdAt: '10 mins ago',
    urgency: 'MEDIUM',
  },
  {
    id: 'tkt_102',
    ticketNumber: 'BK-2026-0002',
    customerName: 'User 3',
    customerPhone: '+91 9000000003',
    vehicleModel: 'TVS iQube ST',
    registrationNumber: 'AP39EF9012',
    serviceType: 'Roadside Assistance',
    status: 'PENDING',
    aiSuggestedFault: 'Roadside Battery Jumpstart & Thermal Cutoff Check',
    aiEstimatedCost: 199,
    aiEstimatedTimeMins: 30,
    location: 'NH-216 Bypass',
    createdAt: '4 mins ago',
    urgency: 'EMERGENCY',
  },
  {
    id: 'tkt_103',
    ticketNumber: 'BK-2026-0003',
    customerName: 'User 2',
    customerPhone: '+91 9000000002',
    vehicleModel: 'Ola S1 Pro Gen2',
    registrationNumber: 'AP39CD5678',
    serviceType: 'Service at Center',
    status: 'COMPLETED',
    aiSuggestedFault: 'Authorized Service Center Diagnostics & Motor Rewinding',
    aiEstimatedCost: 499,
    aiEstimatedTimeMins: 60,
    assignedTechnician: 'Rahul Sharma (Senior EV Tech)',
    location: 'Central Garage Hub 1',
    createdAt: '42 mins ago',
    urgency: 'LOW',
  },
];

export const mockTechnicians: Technician[] = [
  {
    id: 'tech_01',
    name: 'Rahul Sharma',
    phone: '+91 98111 22334',
    serviceCenter: 'Kakinada Main Service Hub',
    skills: ['BMS Diagnostics', 'Ather Master Tech', 'High Voltage Wiring'],
    activeJobsCount: 1,
    completedJobsMonth: 48,
    customerRating: 4.9,
    status: 'ON_JOB',
    distanceKm: 2.4,
  },
  {
    id: 'tech_02',
    name: 'Manoj Kumar',
    phone: '+91 98222 33445',
    serviceCenter: 'Kakinada Main Service Hub',
    skills: ['Ola Telematics Specialist', 'Motor Rewinding', 'Brake Systems'],
    activeJobsCount: 0,
    completedJobsMonth: 52,
    customerRating: 4.8,
    status: 'AVAILABLE',
    distanceKm: 1.1,
  },
  {
    id: 'tech_03',
    name: 'Deepak Varma',
    phone: '+91 98333 44556',
    serviceCenter: 'East Godavari Roadside Hub',
    skills: ['Towing Specialist', 'Emergency Battery Jumpstart', 'TVS Certified'],
    activeJobsCount: 2,
    completedJobsMonth: 41,
    customerRating: 4.7,
    status: 'ON_JOB',
    distanceKm: 5.8,
  },
];

export const mockVendorFleetVehicles: VendorFleetVehicle[] = [
  {
    id: 'flt_001',
    fleetName: 'GreenWheels Delivery Fleet A',
    vendorId: 'VND_GW_01',
    vehicleModel: 'Hero Electric Nyx',
    regNumber: 'AP39FL1001',
    driverName: 'Suresh Kumar',
    currentLat: 16.9891,
    currentLng: 82.2475,
    batteryPercent: 88,
    chargingStatus: 'DISCHARGING',
    lastPing: '30 secs ago',
  },
  {
    id: 'flt_002',
    fleetName: 'GreenWheels Delivery Fleet A',
    vendorId: 'VND_GW_01',
    vehicleModel: 'Hero Electric Nyx',
    regNumber: 'AP39FL1002',
    driverName: 'Ramesh Reddy',
    currentLat: 16.995,
    currentLng: 82.253,
    batteryPercent: 24,
    chargingStatus: 'DISCHARGING',
    lastPing: '15 secs ago',
  },
  {
    id: 'flt_003',
    fleetName: 'UrbanExpress Cargo EV',
    vendorId: 'VND_UE_02',
    vehicleModel: 'Euler HiLoad EV',
    regNumber: 'AP39FL2005',
    driverName: 'Venkatesh P',
    currentLat: 16.972,
    currentLng: 82.231,
    batteryPercent: 95,
    chargingStatus: 'CHARGING',
    lastPing: '1 min ago',
  },
];

// Module 2: Business Performance Mock Data
export const mockFinancialSummaryMetrics: import('./types').FinancialSummaryMetric[] = [
  {
    id: 'fin_01',
    label: 'Gross Revenue',
    value: 1245000,
    formattedValue: '₹12,45,000',
    growthPercent: 18.4,
    isPositive: true,
    previousPeriodValue: '₹10,51,200',
    trend: 'UP',
  },
  {
    id: 'fin_02',
    label: 'Net Profit',
    value: 384000,
    formattedValue: '₹3,84,000',
    growthPercent: 21.2,
    isPositive: true,
    previousPeriodValue: '₹3,16,800',
    trend: 'UP',
  },
  {
    id: 'fin_03',
    label: 'Total Expenses',
    value: 861000,
    formattedValue: '₹8,61,000',
    growthPercent: 12.1,
    isPositive: false,
    previousPeriodValue: '₹7,68,000',
    trend: 'UP',
  },
  {
    id: 'fin_04',
    label: 'Operating Margin',
    value: 30.8,
    formattedValue: '30.8%',
    growthPercent: 3.2,
    isPositive: true,
    previousPeriodValue: '27.6%',
    trend: 'UP',
  },
  {
    id: 'fin_05',
    label: 'Revenue Growth',
    value: 18.4,
    formattedValue: '+18.4%',
    growthPercent: 2.5,
    isPositive: true,
    previousPeriodValue: '+15.9%',
    trend: 'UP',
  },
  {
    id: 'fin_06',
    label: 'Profit Growth',
    value: 21.2,
    formattedValue: '+21.2%',
    growthPercent: 4.1,
    isPositive: true,
    previousPeriodValue: '+17.1%',
    trend: 'UP',
  },
];

export const mockRevenueAnalyticsData: Record<string, import('./types').RevenueAnalyticsPoint[]> = {
  '7D': [
    { period: 'Mon', revenue: 165000, profit: 51000, expenses: 114000, netProfit: 48000, previousRevenue: 142000 },
    { period: 'Tue', revenue: 182000, profit: 56000, expenses: 126000, netProfit: 53000, previousRevenue: 155000 },
    { period: 'Wed', revenue: 174000, profit: 54000, expenses: 120000, netProfit: 50000, previousRevenue: 148000 },
    { period: 'Thu', revenue: 195000, profit: 60000, expenses: 135000, netProfit: 58000, previousRevenue: 162000 },
    { period: 'Fri', revenue: 210000, profit: 65000, expenses: 145000, netProfit: 62000, previousRevenue: 178000 },
    { period: 'Sat', revenue: 240000, profit: 75000, expenses: 165000, netProfit: 71000, previousRevenue: 195000 },
    { period: 'Sun', revenue: 225000, profit: 70000, expenses: 155000, netProfit: 66000, previousRevenue: 184000 },
  ],
  '30D': [
    { period: 'Week 1', revenue: 280000, profit: 86000, expenses: 194000, netProfit: 82000, previousRevenue: 240000 },
    { period: 'Week 2', revenue: 310000, profit: 96000, expenses: 214000, netProfit: 91000, previousRevenue: 265000 },
    { period: 'Week 3', revenue: 325000, profit: 101000, expenses: 224000, netProfit: 97000, previousRevenue: 275000 },
    { period: 'Week 4', revenue: 330000, profit: 101000, expenses: 229000, netProfit: 96000, previousRevenue: 281200 },
  ],
  '6M': [
    { period: 'Jan', revenue: 840000, profit: 240000, expenses: 600000, netProfit: 225000, previousRevenue: 710000 },
    { period: 'Feb', revenue: 920000, profit: 270000, expenses: 650000, netProfit: 255000, previousRevenue: 780000 },
    { period: 'Mar', revenue: 990000, profit: 300000, expenses: 690000, netProfit: 285000, previousRevenue: 820000 },
    { period: 'Apr', revenue: 1080000, profit: 330000, expenses: 750000, netProfit: 315000, previousRevenue: 910000 },
    { period: 'May', revenue: 1160000, profit: 355000, expenses: 805000, netProfit: 340000, previousRevenue: 980000 },
    { period: 'Jun', revenue: 1245000, profit: 384000, expenses: 861000, netProfit: 368000, previousRevenue: 1051200 },
  ],
};

export const mockRevenueBreakdown: import('./types').RevenueSourceBreakdown[] = [
  { id: 'src_01', category: 'Vehicle Sales', amount: 485000, percentage: 38.9, color: '#0280d2' },
  { id: 'src_02', category: 'AMC Subscriptions', amount: 386000, percentage: 31.0, color: '#10b981' },
  { id: 'src_03', category: 'Service Revenue', amount: 185000, percentage: 14.8, color: '#f59e0b' },
  { id: 'src_04', category: 'Spare Parts', amount: 98000, percentage: 7.9, color: '#8b5cf6' },
  { id: 'src_05', category: 'Accessories', amount: 46000, percentage: 3.7, color: '#ec4899' },
  { id: 'src_06', category: 'Insurance Commission', amount: 32000, percentage: 2.6, color: '#06b6d4' },
  { id: 'src_07', category: 'Other Income', amount: 13000, percentage: 1.1, color: '#64748b' },
];

export const mockBranchPerformance: import('./types').BranchPerformance[] = [
  { id: 'br_01', name: 'Kakinada Main Hub', city: 'Kakinada', revenue: 425000, growthPercent: 24.5, servicesCompleted: 482, customerRating: 4.9, isBestPerformer: true },
  { id: 'br_02', name: 'Rajahmundry East', city: 'Rajahmundry', revenue: 312000, growthPercent: 19.2, servicesCompleted: 340, customerRating: 4.8 },
  { id: 'br_03', name: 'Vijayawada Central', city: 'Vijayawada', revenue: 265000, growthPercent: 15.8, servicesCompleted: 285, customerRating: 4.7 },
  { id: 'br_04', name: 'Visakhapatnam Port', city: 'Visakhapatnam', revenue: 148000, growthPercent: 8.4, servicesCompleted: 162, customerRating: 4.5 },
  { id: 'br_05', name: 'Guntur South', city: 'Guntur', revenue: 95000, growthPercent: -3.2, servicesCompleted: 98, customerRating: 4.1, isLowestPerformer: true },
];

export const mockBusinessKpis: import('./types').BusinessKpi[] = [
  { id: 'kpi_01', label: 'Average Daily Revenue', value: '₹41,500', subtext: 'Based on last 30 days', change: '+14.2%', isPositive: true },
  { id: 'kpi_02', label: 'Avg Revenue Per Customer (ARPU)', value: '₹8,412', subtext: 'Active user base', change: '+8.6%', isPositive: true },
  { id: 'kpi_03', label: 'Avg Revenue Per Vehicle (ARPV)', value: '₹12,500', subtext: 'Connected EV fleet', change: '+11.4%', isPositive: true },
  { id: 'kpi_04', label: 'Active AMC Customers', value: '342 Users', subtext: 'Recurring plan model', change: '+22.5%', isPositive: true },
  { id: 'kpi_05', label: 'Customer Retention Rate', value: '94.8%', subtext: 'Year-over-Year', change: '+2.1%', isPositive: true },
  { id: 'kpi_06', label: 'Customer Acquisition Cost (CAC)', value: '₹1,240', subtext: 'Marketing efficiency', change: '-5.4%', isPositive: true },
];

export const mockTopContributors = {
  branches: [
    { id: 'tc_b1', name: 'Kakinada Main Hub', subtitle: '482 Services • 4.9★', value: '₹4,25,000', sharePercent: 34.1 },
    { id: 'tc_b2', name: 'Rajahmundry East', subtitle: '340 Services • 4.8★', value: '₹3,12,000', sharePercent: 25.1 },
    { id: 'tc_b3', name: 'Vijayawada Central', subtitle: '285 Services • 4.7★', value: '₹2,65,000', sharePercent: 21.3 },
    { id: 'tc_b4', name: 'Visakhapatnam Port', subtitle: '162 Services • 4.5★', value: '₹1,48,000', sharePercent: 11.9 },
    { id: 'tc_b5', name: 'Guntur South', subtitle: '98 Services • 4.1★', value: '₹95,000', sharePercent: 7.6 },
  ],
  cities: [
    { id: 'tc_c1', name: 'Kakinada', subtitle: '1 Main Hub • 2 Sub-hubs', value: '₹4,85,000', sharePercent: 38.9 },
    { id: 'tc_c2', name: 'Rajahmundry', subtitle: '1 Main Hub', value: '₹3,12,000', sharePercent: 25.1 },
    { id: 'tc_c3', name: 'Vijayawada', subtitle: '1 Central Hub', value: '₹2,65,000', sharePercent: 21.3 },
    { id: 'tc_c4', name: 'Visakhapatnam', subtitle: '1 Port Hub', value: '₹1,48,000', sharePercent: 11.9 },
    { id: 'tc_c5', name: 'Guntur', subtitle: '1 Branch', value: '₹35,000', sharePercent: 2.8 },
  ],
  products: [
    { id: 'tc_p1', name: 'Ather 450X Apex', subtitle: 'High Performance Scooter', value: '₹3,40,000', sharePercent: 27.3 },
    { id: 'tc_p2', name: '3-Year AMC Membership', subtitle: '₹499 Plan Package', value: '₹2,10,000', sharePercent: 16.8 },
    { id: 'tc_p3', name: 'Ola S1 Pro Gen2', subtitle: 'Urban Commuter', value: '₹1,45,000', sharePercent: 11.6 },
    { id: 'tc_p4', name: 'Lifetime AMC Subscription', subtitle: '₹999 Plan Package', value: '₹1,25,000', sharePercent: 10.0 },
    { id: 'tc_p5', name: 'Service at Doorstep', subtitle: '₹249 Per Visit', value: '₹95,000', sharePercent: 7.6 },
  ],
};

export const mockFinancialAiInsights: import('./types').FinancialInsight[] = [
  {
    id: 'ins_01',
    type: 'POSITIVE',
    text: 'Gross revenue increased by 18.4% compared to last month, driven primarily by AMC subscription renewals.',
    impact: '+₹1,93,800 Revenue Bump',
  },
  {
    id: 'ins_02',
    type: 'HIGHLIGHT',
    text: 'AMC subscriptions contributed 31.0% of total company revenue, generating predictable recurring cash flow.',
    impact: '₹3,86,000 Recurring ARR',
  },
  {
    id: 'ins_03',
    type: 'POSITIVE',
    text: 'Kakinada Main Hub generated the highest revenue this month (₹4.25L) with an exceptional 4.9★ CSAT rating.',
    impact: '34.1% Market Share',
  },
  {
    id: 'ins_04',
    type: 'WARNING',
    text: 'Vehicle servicing revenue in Guntur South decreased by 3.2% due to technician availability bottlenecks.',
    impact: 'Action Required: Reassign Techs',
  },
];

// Module 3: Company Operations Mock Data
export const mockOperationsKpiMetrics: import('./types').OperationsKpiMetric[] = [
  {
    id: 'op_01',
    label: 'Active Service Requests',
    value: '148 Active',
    numericValue: 148,
    trend: 'UP',
    trendPercent: '+8.2%',
    isPositive: true,
    comparisonPeriod: 'vs Yesterday (136)',
  },
  {
    id: 'op_02',
    label: 'Services Completed Today',
    value: '112 Completed',
    numericValue: 112,
    trend: 'UP',
    trendPercent: '+14.5%',
    isPositive: true,
    comparisonPeriod: 'vs Yesterday (98)',
  },
  {
    id: 'op_03',
    label: 'Pending Services',
    value: '26 Pending',
    numericValue: 26,
    trend: 'DOWN',
    trendPercent: '-12.0%',
    isPositive: true,
    comparisonPeriod: 'vs Yesterday (30)',
  },
  {
    id: 'op_04',
    label: 'Overdue Services',
    value: '4 Delayed',
    numericValue: 4,
    trend: 'DOWN',
    trendPercent: '-50.0%',
    isPositive: true,
    comparisonPeriod: 'vs Yesterday (8)',
  },
  {
    id: 'op_05',
    label: 'Average Resolution Time',
    value: '42 Mins',
    numericValue: 42,
    trend: 'DOWN',
    trendPercent: '-6.4%',
    isPositive: true,
    comparisonPeriod: 'vs Target (45 mins)',
  },
  {
    id: 'op_06',
    label: 'SLA Compliance Rate',
    value: '96.4%',
    numericValue: 96.4,
    trend: 'UP',
    trendPercent: '+1.8%',
    isPositive: true,
    comparisonPeriod: 'vs Last Week (94.6%)',
  },
  {
    id: 'op_07',
    label: 'Branches Operating',
    value: '5 / 5 Hubs',
    numericValue: 5,
    trend: 'STABLE',
    trendPercent: '100%',
    isPositive: true,
    comparisonPeriod: 'All Hubs Operational',
  },
  {
    id: 'op_08',
    label: 'Overall Operational Score',
    value: '94 / 100',
    numericValue: 94,
    trend: 'UP',
    trendPercent: '+3 pts',
    isPositive: true,
    comparisonPeriod: 'Optimal Health',
  },
];

export const mockOperationsProgress: import('./types').OperationsProgress = {
  totalJobsToday: 148,
  completedJobs: 112,
  inProgressJobs: 26,
  waitingJobs: 6,
  delayedJobs: 4,
  completionRatePercent: 75.7,
};

export const mockBranchEfficiencyList: import('./types').BranchEfficiency[] = [
  {
    id: 'be_01',
    branchName: 'Kakinada Main Hub',
    city: 'Kakinada',
    servicesCompleted: 48,
    pendingJobs: 4,
    slaCompliancePercent: 98.5,
    customerRating: 4.9,
    operationalScore: 97,
    isBestPerformer: true,
  },
  {
    id: 'be_02',
    branchName: 'Rajahmundry East',
    city: 'Rajahmundry',
    servicesCompleted: 34,
    pendingJobs: 6,
    slaCompliancePercent: 96.2,
    customerRating: 4.8,
    operationalScore: 94,
  },
  {
    id: 'be_03',
    branchName: 'Vijayawada Central',
    city: 'Vijayawada',
    servicesCompleted: 28,
    pendingJobs: 8,
    slaCompliancePercent: 93.8,
    customerRating: 4.7,
    operationalScore: 90,
  },
  {
    id: 'be_04',
    branchName: 'Visakhapatnam Port',
    city: 'Visakhapatnam',
    servicesCompleted: 18,
    pendingJobs: 3,
    slaCompliancePercent: 95.0,
    customerRating: 4.6,
    operationalScore: 91,
  },
  {
    id: 'be_05',
    branchName: 'Guntur South',
    city: 'Guntur',
    servicesCompleted: 12,
    pendingJobs: 5,
    slaCompliancePercent: 88.4,
    customerRating: 4.2,
    operationalScore: 82,
    requiresAttention: true,
  },
];

export const mockServiceCenterHealthList: import('./types').ServiceCenterHealth[] = [
  {
    id: 'sch_01',
    centerName: 'Kakinada Mega Service Hub',
    location: 'Main Road, Kakinada',
    capacityUtilizationPercent: 82,
    activeTechnicians: 14,
    waitingVehicles: 3,
    avgServiceTimeMins: 38,
    currentQueueLength: 4,
    status: 'OPTIMAL',
  },
  {
    id: 'sch_02',
    centerName: 'Rajahmundry EV Station',
    location: 'Danavaipeta, Rajahmundry',
    capacityUtilizationPercent: 74,
    activeTechnicians: 10,
    waitingVehicles: 4,
    avgServiceTimeMins: 41,
    currentQueueLength: 5,
    status: 'OPTIMAL',
  },
  {
    id: 'sch_03',
    centerName: 'Vijayawada Auto Hub',
    location: 'MG Road, Vijayawada',
    capacityUtilizationPercent: 91,
    activeTechnicians: 8,
    waitingVehicles: 7,
    avgServiceTimeMins: 48,
    currentQueueLength: 9,
    status: 'OVERLOADED',
  },
  {
    id: 'sch_04',
    centerName: 'Visakhapatnam Fleet Hub',
    location: 'Gajuwaka, Vizag',
    capacityUtilizationPercent: 68,
    activeTechnicians: 6,
    waitingVehicles: 2,
    avgServiceTimeMins: 35,
    currentQueueLength: 2,
    status: 'OPTIMAL',
  },
  {
    id: 'sch_05',
    centerName: 'Guntur Express Bay',
    location: 'Ring Road, Guntur',
    capacityUtilizationPercent: 86,
    activeTechnicians: 4,
    waitingVehicles: 5,
    avgServiceTimeMins: 52,
    currentQueueLength: 6,
    status: 'MODERATE',
  },
];

export const mockDailyOperationsTimeline: import('./types').OperationalTimelineEvent[] = [
  {
    id: 'tl_01',
    time: '08:00 AM',
    title: 'Morning Shifts Dispatched',
    category: 'SERVICE_STARTED',
    description: '42 field technicians signed in and commenced doorstep EV maintenance routes.',
    impactCount: 42,
    status: 'COMPLETED',
  },
  {
    id: 'tl_02',
    time: '10:30 AM',
    title: 'Peak Service Hours Commenced',
    category: 'PEAK_HOURS',
    description: 'Queue length reached peak capacity across Vijayawada & Kakinada service bays.',
    impactCount: 68,
    status: 'IN_PROGRESS',
  },
  {
    id: 'tl_03',
    time: '12:15 PM',
    title: 'Roadside Assistance Emergency Dispatch',
    category: 'RSA_CALL',
    description: 'Rapid battery swap unit dispatched to AP39FL2005 near Rajahmundry highway.',
    impactCount: 1,
    status: 'COMPLETED',
  },
  {
    id: 'tl_04',
    time: '02:00 PM',
    title: 'Batch AMC Service Milestone',
    category: 'SERVICE_COMPLETED',
    description: '85th AMC routine inspection completed within target 45-minute SLA.',
    impactCount: 85,
    status: 'COMPLETED',
  },
  {
    id: 'tl_05',
    time: '03:45 PM',
    title: 'Guntur Capacity Alert',
    category: 'EMERGENCY',
    description: 'Queue bottleneck detected in Guntur Bay. Automated re-routing triggered.',
    impactCount: 5,
    status: 'ALERT',
  },
];

export const mockOperationsAiInsights: import('./types').OperationsAiInsight[] = [
  {
    id: 'oai_01',
    title: 'Service Completion Rate Growth',
    category: 'EFFICIENCY',
    summary: 'Overall service completion rate improved by 11.4% compared to last week.',
    actionableSuggestion: 'Maintain current technician scheduling matrix to sustain throughput.',
    severity: 'LOW',
  },
  {
    id: 'oai_02',
    title: 'Vijayawada Workload Concentration',
    category: 'WORKLOAD',
    summary: 'Vijayawada Central holds the highest pending workload (9 vehicles in queue, 91% capacity).',
    actionableSuggestion: 'Recommend re-allocating 2 mobile technicians from Visakhapatnam to balance queue.',
    severity: 'HIGH',
  },
  {
    id: 'oai_03',
    title: 'Hyderabad Expansion Performance',
    category: 'TARGET',
    summary: 'Remote fleet monitoring shows Rajahmundry & Kakinada hubs exceeded daily targets by 18%.',
    actionableSuggestion: 'Acknowledge top-performing service bay teams in weekly executive digest.',
    severity: 'LOW',
  },
  {
    id: 'oai_04',
    title: 'Guntur SLA Variance Alert',
    category: 'SLA_RISK',
    summary: 'SLA compliance in Guntur South dropped to 88.4% due to extended motor diagnostic times.',
    actionableSuggestion: 'Deploy AI diagnostic tablet tool to accelerate fault identification by 15 mins.',
    severity: 'MEDIUM',
  },
];

// Module 4: Fleet Intelligence Mock Data
export const mockFleetKpiMetrics: import('./types').FleetKpiMetric[] = [
  {
    id: 'fl_01',
    label: 'Total Registered Vehicles',
    value: '148 EVs',
    numericValue: 148,
    trend: 'UP',
    trendPercent: '+12.4%',
    isPositive: true,
    comparisonPeriod: 'vs Last Month (132)',
  },
  {
    id: 'fl_02',
    label: 'Connected Telemetry EVs',
    value: '144 Online',
    numericValue: 144,
    trend: 'UP',
    trendPercent: '97.3%',
    isPositive: true,
    comparisonPeriod: 'Active IoT Telemetry',
  },
  {
    id: 'fl_03',
    label: 'Active Vehicles on Road',
    value: '118 Active',
    numericValue: 118,
    trend: 'UP',
    trendPercent: '+8.6%',
    isPositive: true,
    comparisonPeriod: 'In-Transit Routes Today',
  },
  {
    id: 'fl_04',
    label: 'Vehicles in Service',
    value: '14 Service',
    numericValue: 14,
    trend: 'STABLE',
    trendPercent: '9.4%',
    isPositive: true,
    comparisonPeriod: 'Scheduled Maintenance',
  },
  {
    id: 'fl_05',
    label: 'Fleet Availability Rate',
    value: '91.8%',
    numericValue: 91.8,
    trend: 'UP',
    trendPercent: '+2.1%',
    isPositive: true,
    comparisonPeriod: 'vs Target (90.0%)',
  },
  {
    id: 'fl_06',
    label: 'Fleet Utilization Rate',
    value: '84.2%',
    numericValue: 84.2,
    trend: 'UP',
    trendPercent: '+14.0%',
    isPositive: true,
    comparisonPeriod: 'vs Last Month (73.8%)',
  },
  {
    id: 'fl_07',
    label: 'Average Fleet Health Score',
    value: '92 / 100',
    numericValue: 92,
    trend: 'UP',
    trendPercent: '+4 pts',
    isPositive: true,
    comparisonPeriod: 'Optimal Condition',
  },
  {
    id: 'fl_08',
    label: 'Critical Vehicles',
    value: '3 Critical',
    numericValue: 3,
    trend: 'DOWN',
    trendPercent: '-50.0%',
    isPositive: true,
    comparisonPeriod: 'Requires Battery Swap',
  },
];

export const mockFleetHealthSummary: import('./types').FleetHealthSummary = {
  overallScore: 92,
  batteryHealthScore: 94,
  motorHealthScore: 91,
  controllerHealthScore: 95,
  chargingPerformanceScore: 89,
  avgRangeKm: 118,
  status: 'OPTIMAL',
};

export const mockVehicleStatusBreakdown: import('./types').VehicleStatusBreakdown[] = [
  { id: 'vst_01', status: 'ONLINE', count: 88, percentage: 59.5, color: '#10b981' },
  { id: 'vst_02', status: 'CHARGING', count: 24, percentage: 16.2, color: '#0280d2' },
  { id: 'vst_03', status: 'IDLE', count: 15, percentage: 10.1, color: '#64748b' },
  { id: 'vst_04', status: 'IN_SERVICE', count: 14, percentage: 9.5, color: '#f59e0b' },
  { id: 'vst_05', status: 'OFFLINE', count: 4, percentage: 2.7, color: '#94a3b8' },
  { id: 'vst_06', status: 'CRITICAL', count: 3, percentage: 2.0, color: '#ef4444' },
];

export const mockBatteryAnalytics: import('./types').BatteryAnalyticsData = {
  avgBatteryHealthSoh: 94.2,
  vehiclesBelow80PercentCount: 6,
  predictedReplacements30Days: 4,
  fastChargingUsagePercent: 28.5,
  avgDegradationRatePer10kKm: 1.2,
  batteryTemperatureOptimalPercent: 96.8,
};

export const mockPredictiveMaintenanceList: import('./types').PredictiveMaintenanceItem[] = [
  {
    id: 'pm_01',
    vehicleModel: 'Ather 450X Apex',
    vin: 'AP39EV2024001',
    issueType: 'BATTERY_DEGRADATION',
    riskLevel: 'CRITICAL',
    dueDate: '2026-07-28',
    aiPrediction: 'SOH degraded to 76.4%. Cell 3 voltage imbalance detected.',
  },
  {
    id: 'pm_02',
    vehicleModel: 'Ola S1 Pro Gen2',
    vin: 'AP39EV2024042',
    issueType: 'MOTOR_THERMAL',
    riskLevel: 'HIGH',
    dueDate: '2026-07-30',
    aiPrediction: 'Stator temperature spike during steep incline runs.',
  },
  {
    id: 'pm_03',
    vehicleModel: 'Euler HiLoad EV',
    vin: 'AP39EV2024089',
    issueType: 'BRAKE_PAD_WEAR',
    riskLevel: 'MEDIUM',
    dueDate: '2026-08-04',
    aiPrediction: 'Regen braking efficiency reduced by 14%. Brake pads at 18%.',
  },
  {
    id: 'pm_04',
    vehicleModel: 'Ather 450S',
    vin: 'AP39EV2024105',
    issueType: 'AMC_EXPIRY',
    riskLevel: 'MEDIUM',
    dueDate: '2026-08-10',
    aiPrediction: 'AMC plan expires in 17 days. Automated renewal prompt sent.',
  },
];

export const mockFleetPerformance: import('./types').FleetPerformanceStat = {
  totalDistanceCoveredKm: 485200,
  fleetEfficiencyKmPerKwh: 4.8,
  avgEnergyConsumptionWhPerKm: 208,
  avgDailyUsageKm: 68.4,
  fleetUtilizationPercent: 84.2,
  downtimePercent: 3.8,
};

export const mockGeographicRegions: import('./types').GeographicRegionCoverage[] = [
  { id: 'geo_01', city: 'Kakinada', activeVehicles: 58, utilizationPercent: 88.5, healthScore: 95, density: 'HIGH', lat: 16.989, lng: 82.247 },
  { id: 'geo_02', city: 'Rajahmundry', activeVehicles: 42, utilizationPercent: 86.0, healthScore: 93, density: 'HIGH', lat: 17.0, lng: 81.78 },
  { id: 'geo_03', city: 'Vijayawada', activeVehicles: 28, utilizationPercent: 82.4, healthScore: 90, density: 'MODERATE', lat: 16.506, lng: 80.648 },
  { id: 'geo_04', city: 'Visakhapatnam', activeVehicles: 12, utilizationPercent: 78.0, healthScore: 92, density: 'EXPANDING', lat: 17.686, lng: 83.218 },
  { id: 'geo_05', city: 'Guntur', activeVehicles: 8, utilizationPercent: 71.5, healthScore: 84, density: 'EXPANDING', lat: 16.306, lng: 80.436 },
];

export const mockFleetAiInsights: import('./types').FleetAiInsight[] = [
  {
    id: 'fai_01',
    title: 'Battery Replacement Forecast',
    category: 'BATTERY',
    summary: '4 vehicles may require battery module replacement within 30 days due to cell degradation.',
    actionableSuggestion: 'Order replacement LFP modules under Ather manufacturer warranty.',
    impact: 'Prevents ₹1.2L Emergency Repair Cost',
  },
  {
    id: 'fai_02',
    title: 'Top Regional Fleet Health',
    category: 'HEALTH',
    summary: 'Kakinada fleet maintains the highest overall health score (95/100) across all 5 operating cities.',
    actionableSuggestion: 'Standardize Kakinada overnight slow-charging protocol across Vijayawada bays.',
    impact: '+2.4% Battery Life Extension',
  },
  {
    id: 'fai_03',
    title: 'Fleet Utilization Surge',
    category: 'UTILIZATION',
    summary: 'Active EV fleet utilization increased by 14.0% this month, reaching an all-time peak of 84.2%.',
    actionableSuggestion: 'Deploy 10 new cargo EVs in Rajahmundry East to satisfy commercial demand.',
    impact: '+₹85,000 Monthly Revenue',
  },
  {
    id: 'fai_04',
    title: 'Preventive AI Maintenance Savings',
    category: 'SAVINGS',
    summary: 'Preventive AI diagnostics reduced on-road vehicle breakdowns by 18.2% YoY.',
    actionableSuggestion: 'Keep real-time motor thermal pings active on all delivery fleet routes.',
    impact: 'Zero Roadside Breakdown Incidents',
  },
];

// Module 5: Department Performance Mock Data
export const mockOrganizationHealth: import('./types').OrganizationHealthData = {
  overallHealthScore: 93,
  departmentEfficiency: 91,
  goalAchievementPercent: 94.8,
  productivityIndex: 92,
  operationalStabilityScore: 95,
  status: 'OPTIMAL',
};

export const mockDepartmentMetrics: import('./types').DepartmentMetric[] = [
  {
    id: 'dept_01',
    departmentName: 'Field & Hub Operations',
    code: 'OPS',
    headOfDepartment: 'Sri Hari Kolusu (Interim Lead)',
    performanceScore: 94,
    kpiAchievementPercent: 96.2,
    targetCompletionPercent: 95.0,
    growthPercent: 14.5,
    status: 'EXCEEDING',
  },
  {
    id: 'dept_02',
    departmentName: 'Technology & AI Engineering',
    code: 'TECH',
    headOfDepartment: 'Ananya Sharma (VP Tech)',
    performanceScore: 98,
    kpiAchievementPercent: 100.0,
    targetCompletionPercent: 98.5,
    growthPercent: 22.0,
    status: 'EXCEEDING',
  },
  {
    id: 'dept_03',
    departmentName: 'Human Resources & Talent',
    code: 'HR',
    headOfDepartment: 'Priya Ramesh (HR Director)',
    performanceScore: 91,
    kpiAchievementPercent: 92.4,
    targetCompletionPercent: 90.0,
    growthPercent: 12.0,
    status: 'ON_TRACK',
  },
  {
    id: 'dept_04',
    departmentName: 'Finance & Accounts',
    code: 'FIN',
    headOfDepartment: 'Vikram Mehta (CFO)',
    performanceScore: 95,
    kpiAchievementPercent: 97.0,
    targetCompletionPercent: 96.0,
    growthPercent: 18.4,
    status: 'EXCEEDING',
  },
  {
    id: 'dept_05',
    departmentName: 'Sales & Growth',
    code: 'SALES',
    headOfDepartment: 'Karthik Raja (Sales VP)',
    performanceScore: 89,
    kpiAchievementPercent: 91.5,
    targetCompletionPercent: 88.0,
    growthPercent: 16.2,
    status: 'ON_TRACK',
  },
  {
    id: 'dept_06',
    departmentName: 'Brand Marketing & PR',
    code: 'MKT',
    headOfDepartment: 'Sneha Roy (Marketing Head)',
    performanceScore: 88,
    kpiAchievementPercent: 89.0,
    targetCompletionPercent: 86.5,
    growthPercent: 10.8,
    status: 'ON_TRACK',
  },
  {
    id: 'dept_07',
    departmentName: 'Customer Support & Success',
    code: 'SVC',
    headOfDepartment: 'Rajesh Kumar (Support Lead)',
    performanceScore: 96,
    kpiAchievementPercent: 98.2,
    targetCompletionPercent: 97.0,
    growthPercent: 19.5,
    status: 'EXCEEDING',
  },
  {
    id: 'dept_08',
    departmentName: 'Inventory & Procurement',
    code: 'SCM',
    headOfDepartment: 'Manoj Verma (SCM Director)',
    performanceScore: 82,
    kpiAchievementPercent: 84.0,
    targetCompletionPercent: 80.0,
    growthPercent: -2.4,
    status: 'ATTENTION_NEEDED',
  },
];

export const mockDepartmentComparisonPoints: import('./types').DepartmentComparisonPoint[] = [
  { metric: 'Productivity', Operations: 92, Technology: 98, HR: 90, Finance: 94, Sales: 88, Service: 96 },
  { metric: 'Revenue Share', Operations: 85, Technology: 90, HR: 70, Finance: 95, Sales: 98, Service: 92 },
  { metric: 'Task Completion', Operations: 94, Technology: 99, HR: 91, Finance: 96, Sales: 89, Service: 97 },
  { metric: 'SLA Adherence', Operations: 96, Technology: 97, HR: 94, Finance: 98, Sales: 85, Service: 98 },
  { metric: 'Customer Rating', Operations: 95, Technology: 96, HR: 92, Finance: 90, Sales: 91, Service: 99 },
  { metric: 'Resource Util.', Operations: 88, Technology: 94, HR: 86, Finance: 92, Sales: 90, Service: 95 },
];

export const mockDepartmentLeaderboard: import('./types').DepartmentLeaderboardItem[] = [
  {
    id: 'lb_01',
    rank: 1,
    departmentName: 'Technology & AI Engineering',
    performanceScore: 98,
    growthPercent: 22.0,
    kpiAchievementPercent: 100.0,
    efficiencyPercent: 97.5,
    badge: 'BEST_PERFORMER',
  },
  {
    id: 'lb_02',
    rank: 2,
    departmentName: 'Customer Support & Success',
    performanceScore: 96,
    growthPercent: 19.5,
    kpiAchievementPercent: 98.2,
    efficiencyPercent: 96.0,
    badge: 'MOST_IMPROVED',
  },
  {
    id: 'lb_03',
    rank: 3,
    departmentName: 'Finance & Accounts',
    performanceScore: 95,
    growthPercent: 18.4,
    kpiAchievementPercent: 97.0,
    efficiencyPercent: 95.8,
  },
  {
    id: 'lb_04',
    rank: 4,
    departmentName: 'Field & Hub Operations',
    performanceScore: 94,
    growthPercent: 14.5,
    kpiAchievementPercent: 96.2,
    efficiencyPercent: 94.0,
  },
  {
    id: 'lb_05',
    rank: 5,
    departmentName: 'Human Resources & Talent',
    performanceScore: 91,
    growthPercent: 12.0,
    kpiAchievementPercent: 92.4,
    efficiencyPercent: 90.5,
  },
  {
    id: 'lb_06',
    rank: 8,
    departmentName: 'Inventory & Procurement',
    performanceScore: 82,
    growthPercent: -2.4,
    kpiAchievementPercent: 84.0,
    efficiencyPercent: 81.0,
    badge: 'REQUIRES_ATTENTION',
  },
];

export const mockCollaborationPairs: import('./types').CollaborationPair[] = [
  {
    id: 'cp_01',
    deptA: 'HR & Talent',
    deptB: 'Field Operations',
    collaborationEfficiencyPercent: 94.5,
    dependenciesCount: 14,
    status: 'OPTIMAL',
    primaryWorkflow: 'Technician onboarding & shift scheduling dispatch',
  },
  {
    id: 'cp_02',
    deptA: 'Technology & AI',
    deptB: 'Customer Service',
    collaborationEfficiencyPercent: 98.0,
    dependenciesCount: 22,
    status: 'OPTIMAL',
    primaryWorkflow: 'AI automated fault diagnosis & instant ticketing',
  },
  {
    id: 'cp_03',
    deptA: 'Sales & Growth',
    deptB: 'Customer Support',
    collaborationEfficiencyPercent: 91.2,
    dependenciesCount: 18,
    status: 'OPTIMAL',
    primaryWorkflow: 'AMC membership renewals & lead conversion',
  },
  {
    id: 'cp_04',
    deptA: 'Procurement & SCM',
    deptB: 'Service Hubs',
    collaborationEfficiencyPercent: 78.4,
    dependenciesCount: 26,
    status: 'BOTTLENECK',
    primaryWorkflow: 'Spare parts supply chain dispatch to Guntur bay',
  },
];

export const mockGoalOkrTrackers: import('./types').GoalOkrTracker[] = [
  {
    id: 'okr_01',
    title: 'Deploy Zero Back-Office Automated HR Dispatch Engine',
    department: 'Technology & HR',
    quarter: 'Q2 2026',
    progressPercent: 95,
    targetValue: '100% Automated',
    currentValue: '95% Deployed',
    status: 'ACTIVE',
  },
  {
    id: 'okr_02',
    title: 'Achieve 35% Operating Profit Margin Company-Wide',
    department: 'Finance & Sales',
    quarter: 'Q2 2026',
    progressPercent: 88,
    targetValue: '35.0% Margin',
    currentValue: '30.8% Margin',
    status: 'ACTIVE',
  },
  {
    id: 'okr_03',
    title: 'Expand Coastline Hub Coverage to 5 Andhra Pradesh Cities',
    department: 'Operations',
    quarter: 'Q2 2026',
    progressPercent: 100,
    targetValue: '5 Cities',
    currentValue: '5 Cities Active',
    status: 'COMPLETED',
  },
  {
    id: 'okr_04',
    title: 'Reduce Spare Parts Lead Time in Guntur Bay to < 24 Hours',
    department: 'Procurement & SCM',
    quarter: 'Q2 2026',
    progressPercent: 62,
    targetValue: '< 24 Hours',
    currentValue: '38 Hours Avg',
    status: 'DELAYED',
  },
  {
    id: 'okr_05',
    title: 'Maintain 99.8% IoT Telemetry Uptime across 148 Connected EVs',
    department: 'Technology',
    quarter: 'Q2 2026',
    progressPercent: 98,
    targetValue: '99.8% Uptime',
    currentValue: '99.6% Uptime',
    status: 'ACTIVE',
  },
  {
    id: 'okr_06',
    title: 'Achieve 98% CSAT Rating for Home Service Dispatches',
    department: 'Customer Support',
    quarter: 'Q2 2026',
    progressPercent: 92,
    targetValue: '98% CSAT',
    currentValue: '96.4% CSAT',
    status: 'ACTIVE',
  },
];

export const mockResourceUtilization: import('./types').ResourceUtilizationData = {
  employeeUtilizationPercent: 91.4,
  budgetUtilizationPercent: 88.2,
  technologyUtilizationPercent: 96.5,
  infrastructureUsagePercent: 84.0,
  departmentCapacityPercent: 89.6,
};

export const mockDepartmentAiInsights: import('./types').DepartmentAiInsight[] = [
  {
    id: 'dai_01',
    title: 'HR Productivity Surge',
    category: 'PRODUCTIVITY',
    summary: 'HR productivity increased by 12.0% following automated technician onboarding workflows.',
    actionableSuggestion: 'Re-allocate 2 HR coordinators to regional talent recruitment drive.',
    impact: '+12.0% HR Throughput',
  },
  {
    id: 'dai_02',
    title: 'Technology Milestone Achievement',
    category: 'MILESTONE',
    summary: 'Technology department completed 100% of quarterly AI diagnostic & Edge Middleware milestones.',
    actionableSuggestion: 'Nominate Tech Engineering team for Founder\'s Excellence Award.',
    impact: '100% Target Met',
  },
  {
    id: 'dai_03',
    title: 'Operations Staffing Variance',
    category: 'STAFFING',
    summary: 'Operations efficiency in Guntur decline by 3.2% due to temporary technician staffing shortages.',
    actionableSuggestion: 'Trigger immediate fast-track hiring for 3 EV certified mechanics in Guntur.',
    impact: 'Resolves Guntur Queue Bottleneck',
  },
  {
    id: 'dai_04',
    title: 'Service Customer Satisfaction Peak',
    category: 'CSAT',
    summary: 'Customer Service department exceeded quarterly CSAT targets, reaching a record 4.9★ rating.',
    actionableSuggestion: 'Share customer feedback best practices across all sales touchpoints.',
    impact: '98.2% Customer CSAT',
  },
];

// Module 6: AI Command Center Mock Data
export const mockExecutiveAiBriefing = {
  greeting: 'Good morning, Sri Hari.',
  summaryText: 'Company revenue has increased by 18.4% compared to last month, reaching ₹12.45L. Connected EV fleet utilization remains healthy at 84.2% with 91.8% availability. Kakinada Main Hub continues to be our top-performing regional center (₹4.25L, 4.9★ CSAT), while Guntur South is experiencing minor service queue bottlenecks due to technician capacity. Three executive approvals are currently pending your sign-off.',
  lastAnalysisTime: 'Today at 08:30 AM (Realtime IoT Sync)',
};

export const mockCategoryInsights: import('./types').CategoryInsightItem[] = [
  {
    id: 'ci_01',
    category: 'Revenue',
    insightText: 'AMC subscription renewals grew 31.0% YoY, generating ₹3.86L in predictable monthly recurring revenue.',
    trend: 'POSITIVE',
    metricHighlight: '+31.0% ARR',
  },
  {
    id: 'ci_02',
    category: 'Operations',
    insightText: 'Average service resolution time dropped to 42 minutes across active regional hubs.',
    trend: 'POSITIVE',
    metricHighlight: '42 Mins Avg',
  },
  {
    id: 'ci_03',
    category: 'Fleet',
    insightText: 'IoT telemetry pings show 94.2% average State of Health (SOH) across 148 registered EVs.',
    trend: 'POSITIVE',
    metricHighlight: '94.2% SOH',
  },
  {
    id: 'ci_04',
    category: 'Customers',
    insightText: 'Customer retention rate hit an all-time high of 94.8% supported by 1-click doorstep servicing.',
    trend: 'POSITIVE',
    metricHighlight: '94.8% Retention',
  },
  {
    id: 'ci_05',
    category: 'Employees',
    insightText: 'Technician productivity increased 14.2% following automated AI fault diagnosis deployment.',
    trend: 'POSITIVE',
    metricHighlight: '+14.2% Output',
  },
  {
    id: 'ci_06',
    category: 'Departments',
    insightText: 'Technology & AI Engineering department completed 100% of quarterly OKR milestones.',
    trend: 'POSITIVE',
    metricHighlight: '100% OKR Met',
  },
  {
    id: 'ci_07',
    category: 'Service Centers',
    insightText: 'Guntur South queue length spiked to 6 vehicles. Automated re-routing triggered.',
    trend: 'ATTENTION',
    metricHighlight: 'Action Required',
  },
];

export const mockPredictiveForecasts: import('./types').PredictiveForecastItem[] = [
  {
    id: 'pf_01',
    metricName: 'Gross Monthly Revenue',
    category: 'REVENUE',
    currentValue: '₹12.45 Lakhs',
    forecastedValue: '₹14.80 Lakhs',
    forecastPeriod: 'Next Month (Jul 2026)',
    confidencePercent: 94,
    trend: 'UP',
  },
  {
    id: 'pf_02',
    metricName: 'Daily Service Booking Demand',
    category: 'DEMAND',
    currentValue: '148 Jobs/Day',
    forecastedValue: '175 Jobs/Day',
    forecastPeriod: 'Next 14 Days',
    confidencePercent: 91,
    trend: 'UP',
  },
  {
    id: 'pf_03',
    metricName: 'Connected Fleet Growth',
    category: 'FLEET',
    currentValue: '148 EVs',
    forecastedValue: '180 EVs',
    forecastPeriod: 'Q3 2026',
    confidencePercent: 96,
    trend: 'UP',
  },
  {
    id: 'pf_04',
    metricName: 'Active AMC Customer Base',
    category: 'CUSTOMERS',
    currentValue: '342 Members',
    forecastedValue: '420 Members',
    forecastPeriod: 'Next 30 Days',
    confidencePercent: 89,
    trend: 'UP',
  },
  {
    id: 'pf_05',
    metricName: 'Battery Module Replacements',
    category: 'MAINTENANCE',
    currentValue: '4 Swaps',
    forecastedValue: '12 Swaps Needed',
    forecastPeriod: 'Next 60 Days',
    confidencePercent: 92,
    trend: 'UP',
  },
  {
    id: 'pf_06',
    metricName: 'Spare Parts Inventory Level',
    category: 'INVENTORY',
    currentValue: '85% Stocked',
    forecastedValue: '62% (Restock Required)',
    forecastPeriod: 'Next 21 Days',
    confidencePercent: 88,
    trend: 'DOWN',
  },
];

export const mockRiskDetections: import('./types').RiskDetectionItem[] = [
  {
    id: 'rk_01',
    title: 'Guntur Technician Capacity Bottleneck',
    severity: 'HIGH',
    category: 'STAFFING',
    description: 'Service bay queue length in Guntur South exceeding optimal thresholds, risking a 6.2% drop in regional SLA compliance.',
    impactPotential: 'SLA Risk: 88.4%',
    recommendedMitigation: 'Deploy 2 mobile service vans from Vijayawada to absorb peak demand.',
  },
  {
    id: 'rk_02',
    title: 'Battery Cell Degradation Spike in 4 EVs',
    severity: 'MEDIUM',
    category: 'BATTERY',
    description: 'BMS telemetry detected cell voltage imbalance in 4 older Ather 450X packs operating under heavy fast-charging routines.',
    impactPotential: 'Potential On-road Breakdown',
    recommendedMitigation: 'Schedule preventive battery module replacement under warranty next week.',
  },
  {
    id: 'rk_03',
    title: 'Spare Parts Stock Shortage for Motor Controllers',
    severity: 'MEDIUM',
    category: 'INVENTORY',
    description: 'Current warehouse inventory for Ather MCU controllers at 3 units, below 14-day safety threshold.',
    impactPotential: 'Delay in Repair Turnaround',
    recommendedMitigation: 'Issue automated purchase order to Ather OEM supplier.',
  },
];

export const mockOpportunities: import('./types').OpportunityItem[] = [
  {
    id: 'op_01',
    title: 'Expand AMC Subscription Campaigns in Rajahmundry',
    category: 'EXPANSION',
    description: 'Rajahmundry region shows 86% fleet utilization with only 40% AMC adoption.',
    estimatedRevenueGain: '+₹1.40 Lakhs/Month',
    difficulty: 'EASY',
  },
  {
    id: 'op_02',
    title: 'Launch Doorstep Service at Home in Visakhapatnam',
    category: 'SERVICE',
    description: 'Vizag port hub currently operates center-only servicing. High demand for doorstep service.',
    estimatedRevenueGain: '+₹95,000/Month',
    difficulty: 'MODERATE',
  },
  {
    id: 'op_03',
    title: 'Promote 3-Year Corporate Fleet AMC Packages',
    category: 'MARKETING',
    description: 'Commercial fleet vendors in Kakinada seeking long-term maintenance contracts.',
    estimatedRevenueGain: '+₹2.50 Lakhs Upfront',
    difficulty: 'EASY',
  },
];

export const mockAiRecommendations: import('./types').AiRecommendationItem[] = [
  {
    id: 'rec_01',
    actionTitle: 'Re-allocate 2 Mobile Service Vans to Guntur South',
    category: 'Operations',
    priority: 'HIGH',
    description: 'Absorbs peak queue bottleneck and restores SLA compliance from 88.4% to 95%+. ',
    impactSummary: 'Eliminates Queue Lag',
  },
  {
    id: 'rec_02',
    actionTitle: 'Order 15 LFP Battery Modules & MCU Controllers',
    category: 'Fleet',
    priority: 'HIGH',
    description: 'Restocks critical inventory before predicted 60-day replacement demand surge.',
    impactSummary: 'Secures Supply Chain',
  },
  {
    id: 'rec_03',
    actionTitle: 'Fast-Track Hiring for 4 Certified EV Mechanics in Vizag & Guntur',
    category: 'HR',
    priority: 'MEDIUM',
    description: 'Fills operational staffing gap to support 180 connected EV fleet expansion target.',
    impactSummary: 'Scales Roster',
  },
  {
    id: 'rec_04',
    actionTitle: 'Launch Automated Renewal Prompts for 58 Expiring AMC Plans',
    category: 'Revenue',
    priority: 'HIGH',
    description: 'Retains ₹2.90L recurring revenue with automated WhatsApp renewal flows.',
    impactSummary: 'Retains ₹2.9L ARR',
  },
];

export const mockAiTimelineLogs: import('./types').AiTimelineLog[] = [
  {
    id: 'atl_01',
    timestamp: '08:30 AM Today',
    eventTitle: 'Realtime Executive Briefing Synthesized',
    type: 'INSIGHT_SYNTHESIZED',
    summary: 'Analyzed 148 IoT EV telemetry streams, ₹12.45L financial ledger, and 5 regional hub queues.',
  },
  {
    id: 'atl_02',
    timestamp: '07:45 AM Today',
    eventTitle: 'Predictive Battery Degradation Scan Complete',
    type: 'ANALYSIS_COMPLETE',
    summary: 'Scanned 148 BMS battery packs. Identified 4 vehicles requiring proactive module swap within 30 days.',
  },
  {
    id: 'atl_03',
    timestamp: 'Yesterday 11:15 PM',
    eventTitle: 'Guntur Workload Risk Detected',
    type: 'RISK_DETECTED',
    summary: 'Queue capacity threshold exceeded in Guntur bay. Suggested mobile van re-allocation.',
  },
  {
    id: 'atl_04',
    timestamp: 'Yesterday 06:00 PM',
    eventTitle: 'Q3 Revenue Forecast Updated',
    type: 'FORECAST_UPDATED',
    summary: 'Updated Q3 monthly revenue projection to ₹14.80L with 94% statistical confidence.',
  },
];

export const mockInitialChatMessages: import('./types').ChatMessage[] = [
  {
    id: 'msg_01',
    sender: 'AI',
    text: 'Hello Sri Hari. I am your Executive AI Assistant. How can I assist your strategic decision-making today?',
    timestamp: '08:30 AM',
    metrics: [
      { label: 'Revenue Growth', value: '+18.4%' },
      { label: 'Fleet Health', value: '92/100' },
      { label: 'Active Hubs', value: '5 / 5' },
    ],
  },
];

// Module 8: CEO Action Center Mock Data
export const mockDecisionSummaryMetrics: import('./types').DecisionSummaryMetric[] = [
  { id: 'dsm_01', label: 'Pending Approvals', count: 6, trend: '+2 today', avgDecisionTime: '3.2 Hours', badgeColor: 'bg-amber-50 text-amber-800 border-amber-300' },
  { id: 'dsm_02', label: 'High Priority Decisions', count: 3, trend: 'Needs Signoff', avgDecisionTime: '1.5 Hours', badgeColor: 'bg-red-50 text-red-800 border-red-300' },
  { id: 'dsm_03', label: 'Awaiting COO Review', count: 4, trend: 'In Pipeline', avgDecisionTime: '4.8 Hours', badgeColor: 'bg-sky-50 text-sky-800 border-sky-300' },
  { id: 'dsm_04', label: 'Completed Today', count: 12, trend: '100% On Time', avgDecisionTime: '45 Mins', badgeColor: 'bg-emerald-50 text-emerald-800 border-emerald-300' },
  { id: 'dsm_05', label: 'Delegated Actions', count: 5, trend: 'Active Tracking', avgDecisionTime: '2.4 Days', badgeColor: 'bg-purple-50 text-purple-800 border-purple-300' },
  { id: 'dsm_06', label: 'Escalated Requests', count: 1, trend: 'Immediate Action', avgDecisionTime: 'Urgent', badgeColor: 'bg-rose-50 text-rose-800 border-rose-300' },
];

export const mockDecisionRequests: import('./types').DecisionRequestItem[] = [
  {
    id: 'req_01',
    title: 'Approve ₹48 Lakh Commercial EV Fleet Procurement',
    category: 'Finance',
    branch: 'Kakinada Main Hub',
    submittedBy: 'Vikram Mehta',
    submittedByRole: 'CFO',
    businessImpact: 'Expands commercial delivery fleet capacity by 25 Euler EV units to satisfy surge in coastal logistics contracts.',
    financialImpact: 'CapEx: ₹48.00L (Approved Q2 Budget: ₹60L). Expected Payback: 11 Months.',
    dueDate: 'Today, 5:00 PM',
    priority: 'HIGH',
    riskLevel: 'LOW',
    aiRecommendation: 'Approval Recommended. CapEx fits Q2 budget limits and vendor offers 3-year free battery warranty.',
    aiConfidencePercent: 96,
    status: 'PENDING',
    workflowStage: 'CEO_APPROVAL',
  },
  {
    id: 'req_02',
    title: 'Authorize Fast-Track Hiring of 4 EV Technicians in Vizag & Guntur',
    category: 'HR',
    branch: 'Guntur South & Vizag Port',
    submittedBy: 'Priya Ramesh',
    submittedByRole: 'HR Director',
    businessImpact: 'Resolves Guntur service bay queue bottlenecks and prepares Vizag hub for doorstep service launch.',
    financialImpact: 'OpEx: ₹1.60L/Month total payroll increase. Offset by predicted ₹2.35L service revenue gain.',
    dueDate: 'Tomorrow, 12:00 PM',
    priority: 'HIGH',
    riskLevel: 'LOW',
    aiRecommendation: 'Approval Recommended. Eliminates current SLA queue penalty risk in Guntur bay.',
    aiConfidencePercent: 94,
    status: 'PENDING',
    workflowStage: 'CEO_APPROVAL',
  },
  {
    id: 'req_03',
    title: 'Approve Expansion into Vijayawada Central Service Center Phase 2',
    category: 'Operations',
    branch: 'Vijayawada Central',
    submittedBy: 'Sri Hari Kolusu',
    submittedByRole: 'Interim Ops Lead',
    businessImpact: 'Adds 4 new fast-charging bays and 2 high-voltage repair bays in Vijayawada hub.',
    financialImpact: 'CapEx: ₹18.50 Lakhs.',
    dueDate: '25 Jun 2026',
    priority: 'MEDIUM',
    riskLevel: 'MEDIUM',
    aiRecommendation: 'Approval Recommended with Phased Funding. Phase 1 ROI exceeded target by 14%.',
    aiConfidencePercent: 91,
    status: 'PENDING',
    workflowStage: 'COO_REVIEW',
  },
  {
    id: 'req_04',
    title: 'Order 15 LFP Replacement Battery Modules & MCU Controllers',
    category: 'Fleet',
    branch: 'All Coastal Hubs',
    submittedBy: 'Ananya Sharma',
    submittedByRole: 'VP Tech & BMS Lead',
    businessImpact: 'Proactively restocks critical spares before predicted 60-day replacement demand surge.',
    financialImpact: 'Procurement Cost: ₹12.20 Lakhs.',
    dueDate: '26 Jun 2026',
    priority: 'HIGH',
    riskLevel: 'MEDIUM',
    aiRecommendation: 'Approval Recommended. Prevents vehicle downtime for 12 fleet EVs reaching 80% SOH.',
    aiConfidencePercent: 95,
    status: 'PENDING',
    workflowStage: 'CEO_APPROVAL',
  },
  {
    id: 'req_05',
    title: 'Approve InnoVibe Edge Telemetry Middleware v2.4 Security Policy Release',
    category: 'Technology',
    branch: 'Corporate HQ',
    submittedBy: 'Ananya Sharma',
    submittedByRole: 'VP Tech',
    businessImpact: 'Upgrades IoT encryption and reduces telemetry latency to < 100ms for connected EVs.',
    financialImpact: 'Included in Tech R&D Budget (Zero incremental cost).',
    dueDate: '27 Jun 2026',
    priority: 'MEDIUM',
    riskLevel: 'LOW',
    aiRecommendation: 'Approval Recommended. Passed 100% of automated security penetration tests.',
    aiConfidencePercent: 98,
    status: 'PENDING',
    workflowStage: 'CEO_APPROVAL',
  },
  {
    id: 'req_06',
    title: 'Revise Q3 Marketing Budget for Tier-2 City AMC Awareness Drive',
    category: 'Finance',
    branch: 'Rajahmundry & Eluru',
    submittedBy: 'Sneha Roy',
    submittedByRole: 'Marketing Head',
    businessImpact: 'Targeted campaign to boost AMC subscription rate from 40% to 65% in Rajahmundry East.',
    financialImpact: 'Budget Re-allocation: ₹3.50 Lakhs from brand PR to digital performance ads.',
    dueDate: '28 Jun 2026',
    priority: 'LOW',
    riskLevel: 'LOW',
    aiRecommendation: 'Approval Recommended. Re-allocation has neutral net cash impact with high conversion probability.',
    aiConfidencePercent: 90,
    status: 'PENDING',
    workflowStage: 'DEPT_HEAD',
  },
];

export const mockStrategicInitiatives: import('./types').StrategicInitiativeItem[] = [
  {
    id: 'init_01',
    title: 'South India Coastal Region EV Fleet Expansion',
    category: 'Regional Growth',
    progressPercent: 78,
    budgetUsed: '₹1.82 Crore',
    totalBudget: '₹2.40 Crore',
    timeline: 'Q1 2026 - Q4 2026',
    sponsor: 'Sri Hari Kolusu (CEO)',
    currentRisk: 'Low (Guntur staffing bottleneck actively being resolved)',
    nextMilestone: 'Launch Visakhapatnam Port Doorstep Service Hub (Jul 15)',
  },
  {
    id: 'init_02',
    title: 'Zero Back-Office Autonomous AI Dispatch Engine',
    category: 'Technology & AI',
    progressPercent: 92,
    budgetUsed: '₹42.00 Lakhs',
    totalBudget: '₹45.00 Lakhs',
    timeline: 'Q2 2026 Complete',
    sponsor: 'Ananya Sharma (VP Tech)',
    currentRisk: 'Low (Passed load testing at 1,000 requests/min)',
    nextMilestone: 'Deploy Edge Middleware 2.4 to all connected Ather EVs',
  },
  {
    id: 'init_03',
    title: 'Next-Gen Ultra Fast Charging Grid Rollout (150kW DC)',
    category: 'Infrastructure',
    progressPercent: 45,
    budgetUsed: '₹65.00 Lakhs',
    totalBudget: '₹1.50 Crore',
    timeline: 'Q2 2026 - Q1 2027',
    sponsor: 'Vikram Mehta (CFO)',
    currentRisk: 'Medium (Grid power clearance pending in Kakinada Port)',
    nextMilestone: 'Secure State Electricity Board Approval for 3 Sub-stations',
  },
  {
    id: 'init_04',
    title: '3-Year Commercial Fleet Lifetime AMC Package Launch',
    category: 'Commercial Sales',
    progressPercent: 65,
    budgetUsed: '₹12.50 Lakhs',
    totalBudget: '₹20.00 Lakhs',
    timeline: 'Q2 2026',
    sponsor: 'Karthik Raja (Sales VP)',
    currentRisk: 'Low (14 B2B commercial logistics partners in pipeline)',
    nextMilestone: 'Sign Master Service Agreement with 3 Logistics Vendors',
  },
];

export const mockExecutiveCalendarEvents: import('./types').ExecutiveCalendarItem[] = [
  {
    id: 'cal_01',
    title: 'Q2 Board of Directors Strategic Review Meeting',
    category: 'BOARD',
    dateTime: 'Tomorrow, 10:00 AM - 12:30 PM',
    location: 'Corporate HQ Boardroom / Virtual Hybrid',
    attendeesCount: 8,
    priority: 'HIGH',
  },
  {
    id: 'cal_02',
    title: 'Kakinada Main Hub Operational Inspection & Fleet Review',
    category: 'VISIT',
    dateTime: 'Fri, 27 Jun 2026, 09:00 AM',
    location: 'Kakinada Main Hub, Beach Road',
    attendeesCount: 12,
    priority: 'HIGH',
  },
  {
    id: 'cal_03',
    title: 'Series-B Investor Update & Growth Pitch Call',
    category: 'INVESTOR',
    dateTime: 'Mon, 30 Jun 2026, 03:00 PM',
    location: 'Virtual Conference',
    attendeesCount: 5,
    priority: 'HIGH',
  },
  {
    id: 'cal_04',
    title: 'Q3 Enterprise OKR Planning & Department Allocation',
    category: 'REVIEW',
    dateTime: 'Wed, 02 Jul 2026, 11:00 AM',
    location: 'Executive Conference Room',
    attendeesCount: 10,
    priority: 'MEDIUM',
  },
];

export const mockDelegatedTasks: import('./types').DelegatedTaskItem[] = [
  {
    id: 'del_01',
    taskTitle: 'Negotiate Bulk LFP Battery Cell Discounts with OEM Supplier',
    assignedTo: 'Vikram Mehta (CFO)',
    department: 'Finance & Procurement',
    deadline: '28 Jun 2026',
    progressPercent: 85,
    lastUpdate: 'Term sheet agreed; final legal review in progress.',
    status: 'ON_TRACK',
  },
  {
    id: 'del_02',
    taskTitle: 'Recruit 4 EV Certified Mechanics for Guntur & Vizag Hubs',
    assignedTo: 'Priya Ramesh (HR Director)',
    department: 'Human Resources',
    deadline: '30 Jun 2026',
    progressPercent: 70,
    lastUpdate: '8 candidate interviews completed; offer letters queued.',
    status: 'ON_TRACK',
  },
  {
    id: 'del_03',
    taskTitle: 'Deploy WhatsApp 1-Click Servicing Bot for Commercial Clients',
    assignedTo: 'Ananya Sharma (VP Tech)',
    department: 'Technology',
    deadline: '25 Jun 2026',
    progressPercent: 95,
    lastUpdate: 'UAT testing completed; live staging deployment today.',
    status: 'ON_TRACK',
  },
  {
    id: 'del_04',
    taskTitle: 'Resolve Guntur Service Bay SLA Bottleneck',
    assignedTo: 'Sri Hari Kolusu (Interim Lead)',
    department: 'Operations',
    deadline: '24 Jun 2026',
    progressPercent: 60,
    lastUpdate: 'Mobile van re-allocation requested for CEO signoff.',
    status: 'DELAYED',
  },
];

export const mockExecutiveNotes: import('./types').ExecutiveNoteItem[] = [
  {
    id: 'note_01',
    title: 'Board Meeting Focus: Q3 Expansion Margin Targets',
    category: 'BOARD',
    content: 'Emphasize that software-led AMC subscriptions will push operating margin from 30.8% to 35.0% by Q4. Highlight zero roadside breakdown record.',
    pinned: true,
    timestamp: 'Today at 08:15 AM',
  },
  {
    id: 'note_02',
    title: 'Kakinada Hub Visit Checklist',
    category: 'STRATEGY',
    content: 'Inspect fast-charging station #3, review technician shift logs, meet commercial logistics partner leads, and present Best Performer trophy.',
    pinned: true,
    timestamp: 'Yesterday at 05:40 PM',
  },
  {
    id: 'note_03',
    title: 'Follow up with CFO on CapEx Amortization Model',
    category: 'REMINDER',
    content: 'Check if 11-month payback calculation for the ₹48L fleet procurement includes tax benefits on EV depreciation.',
    pinned: false,
    timestamp: '22 Jun 2026',
  },
];

export const mockAiDecisionAdviceList: Record<string, import('./types').AiDecisionAdvice> = {
  req_01: {
    requestId: 'req_01',
    summary: 'Procurement request for ₹48 Lakhs commercial EV fleet aligns directly with approved Q2 CapEx limits and accelerates regional logistics revenue.',
    pros: [
      'Increases commercial delivery fleet capacity by 25 EVs.',
      'Generates an estimated ₹4.35L in incremental monthly revenue.',
      'Includes 3-year OEM battery warranty with zero breakdown penalty.',
    ],
    risks: [
      'Requires quick onboarding of 2 commercial fleet drivers.',
      'Slight increase in insurance premium expenses (+₹15k/mo).',
    ],
    alternatives: [
      'Option A: Approve full 25 EV fleet procurement immediately (Recommended).',
      'Option B: Approve 15 EVs today and defer 10 EVs to Q3.',
    ],
    confidenceScore: 96,
  },
  req_02: {
    requestId: 'req_02',
    summary: 'Fast-track technician hiring directly resolves Guntur service queue backlog and enables doorstep service launch in Visakhapatnam.',
    pros: [
      'Restores Guntur bay SLA compliance to >95%.',
      'Generates ₹2.35L monthly service revenue vs ₹1.60L payroll cost.',
      'Improves technician-to-EV ratio in coastal hubs.',
    ],
    risks: [
      'Requires 5-day EV safety training before active deployment.',
    ],
    alternatives: [
      'Option A: Fast-track hire 4 technicians now (Recommended).',
      'Option B: Re-allocate 2 mechanics permanently from Kakinada to Guntur.',
    ],
    confidenceScore: 94,
  },
};

// Module 9: Communication Hub Mock Data
export const mockCommSummaryMetrics: import('./types').CommSummaryMetric[] = [
  { id: 'csm_01', label: 'Announcements Published', value: 14, trend: '+3 this month', comparison: '100% Reach across hubs', badgeColor: 'bg-sky-50 text-sky-800 border-sky-300' },
  { id: 'csm_02', label: 'Active C-Suite Threads', value: 8, trend: '4 Decisions Logged', comparison: 'Avg 12 Mins Response', badgeColor: 'bg-indigo-50 text-indigo-800 border-indigo-300' },
  { id: 'csm_03', label: 'Scheduled Exec Meetings', value: 6, trend: 'Board & Investor Sync', comparison: 'Next: Tomorrow 10:00 AM', badgeColor: 'bg-purple-50 text-purple-800 border-purple-300' },
  { id: 'csm_04', label: 'Pending Exec Responses', value: 2, trend: 'Signoff Needed', comparison: 'High Priority', badgeColor: 'bg-amber-50 text-amber-800 border-amber-300' },
  { id: 'csm_05', label: 'Organization Reach', value: '100%', trend: '148 Active Employees', comparison: '5 Coastal Hubs Active', badgeColor: 'bg-emerald-50 text-emerald-800 border-emerald-300' },
  { id: 'csm_06', label: 'Communication Index', value: '96.2%', trend: '+4.8% YoY Growth', comparison: 'Top Tier Executive Clarity', badgeColor: 'bg-sky-50 text-sky-800 border-sky-300' },
];

export const mockExecutiveAnnouncements: import('./types').ExecutiveAnnouncement[] = [
  {
    id: 'ann_01',
    title: 'InnoVibe Achieves Record ₹12.45 Lakhs Monthly Revenue & Zero Roadside Breakdown Milestone',
    category: 'COMPANY_UPDATE',
    publishedAt: 'Today at 08:30 AM',
    author: 'Sri Hari Kolusu (CEO)',
    targetAudience: 'All Employees & Stakeholders (148 Staff)',
    priority: 'HIGH',
    richTextSnippet: 'Dear InnoVibe Team, I am thrilled to share that our coastal Andhra Pradesh EV ecosystem reached ₹12.45L monthly revenue with 94.2% fleet battery SOH. Special congratulations to Kakinada Main Hub for earning the Q2 Best Performer trophy!',
    viewsCount: 142,
    readPercent: 96.0,
    acknowledgedPercent: 92.5,
    commentsCount: 18,
  },
  {
    id: 'ann_02',
    title: 'Official Launch of Visakhapatnam Port Doorstep EV Servicing Hub',
    category: 'BRANCH_LAUNCH',
    publishedAt: 'Yesterday at 04:15 PM',
    author: 'Sri Hari Kolusu (CEO)',
    targetAudience: 'Field Operations & Service Teams',
    priority: 'HIGH',
    richTextSnippet: 'Effective July 1st, our Visakhapatnam Port hub will commence 1-click doorstep servicing for Ather and Euler commercial EV fleets. 2 mobile service vans have been allocated.',
    viewsCount: 128,
    readPercent: 91.2,
    acknowledgedPercent: 88.0,
    commentsCount: 12,
  },
  {
    id: 'ann_03',
    title: 'InnoVibe Edge Telemetry Middleware v2.4 Security & Policy Briefing',
    category: 'POLICY',
    publishedAt: '22 Jun 2026',
    author: 'Ananya Sharma (VP Tech)',
    targetAudience: 'Technology, Engineering & Operations Leads',
    priority: 'NORMAL',
    richTextSnippet: 'Edge Middleware v2.4 introduces end-to-end BMS encryption and reduces latency to < 100ms across all active connected vehicles. All technicians are instructed to verify firmware pings during servicing.',
    viewsCount: 110,
    readPercent: 88.5,
    acknowledgedPercent: 85.0,
    commentsCount: 6,
  },
];

export const mockLeadershipThreads: import('./types').LeadershipThread[] = [
  {
    id: 'th_01',
    topicTitle: 'Q3 Coastal Hub Expansion & Fleet CapEx Allocation (₹60L)',
    leadParticipant: 'Sri Hari (CEO) & Vikram Mehta (CFO)',
    departmentFocus: 'Finance & Strategy',
    lastActivity: '15 Mins ago by Vikram Mehta',
    messagesCount: 14,
    actionItemsCount: 3,
    status: 'ACTIVE_DISCUSSION',
    summarySnippet: 'CFO confirmed CapEx payback period of 11 months for 25 Euler EV units in Kakinada. Awaiting final board signoff tomorrow.',
  },
  {
    id: 'th_02',
    topicTitle: 'Resolving Guntur Bay Technician SLA Queue Bottleneck',
    leadParticipant: 'Sri Hari (CEO) & Priya Ramesh (HR)',
    departmentFocus: 'Operations & HR',
    lastActivity: '1 Hour ago by Priya Ramesh',
    messagesCount: 9,
    actionItemsCount: 2,
    status: 'DECISION_LOGGED',
    summarySnippet: 'Approved fast-track hiring of 4 certified EV mechanics and re-allocated 2 mobile vans from Vijayawada to absorb peak queue.',
  },
  {
    id: 'th_03',
    topicTitle: 'Zero Back-Office Autonomous AI Dispatch Engine Integration',
    leadParticipant: 'Sri Hari (CEO) & Ananya Sharma (VP Tech)',
    departmentFocus: 'Technology & AI',
    lastActivity: 'Yesterday at 06:30 PM',
    messagesCount: 22,
    actionItemsCount: 4,
    status: 'RESOLVED',
    summarySnippet: 'Completed load testing at 1,000 requests/min. Automated WhatsApp booking dispatch live in staging with zero human back-office lag.',
  },
];

export const mockExecutiveMeetings: import('./types').ExecutiveMeetingItem[] = [
  {
    id: 'mtg_01',
    title: 'Q2 Board of Directors Strategic Review Meeting',
    meetingType: 'BOARD',
    dateTime: 'Tomorrow, 10:00 AM - 12:30 PM',
    location: 'Corporate HQ Boardroom / Virtual Hybrid',
    participants: ['Sri Hari Kolusu (CEO)', 'Vikram Mehta (CFO)', 'Ananya Sharma (VP Tech)', 'Board Members (5)'],
    aiMeetingSummary: 'AI Pre-Meeting Briefing: Operating margins up +4.2% YoY. Software-led AMC subscriptions generated ₹3.86L ARR. Recommended presentation focus: coastal hub expansion ROI.',
    actionItems: ['Prepare Q2 Financial Slide Deck', 'Compile EV Fleet Battery Health SOH Audit', 'Finalize Series-B Pitch Outline'],
    status: 'UPCOMING',
  },
  {
    id: 'mtg_02',
    title: 'Weekly C-Suite Operations & Strategic Alignment Sync',
    meetingType: 'LEADERSHIP',
    dateTime: 'Fri, 27 Jun 2026, 09:00 AM',
    location: 'Executive Conference Room',
    participants: ['Sri Hari (CEO)', 'COO Lead', 'CFO', 'VP Tech', 'HR Director', 'Sales VP'],
    actionItems: ['Review Guntur mobile van re-allocation', 'Approve Q3 marketing budget shift'],
    status: 'UPCOMING',
  },
  {
    id: 'mtg_03',
    title: 'Series-B Venture Investor Growth Update Call',
    meetingType: 'INVESTOR',
    dateTime: 'Mon, 30 Jun 2026, 03:00 PM',
    location: 'Virtual Zoom Executive Suite',
    participants: ['Sri Hari (CEO)', 'Vikram Mehta (CFO)', 'Lead Investor Partners (3)'],
    actionItems: ['Send Q2 Financial Audit Report', 'Share 148 Connected EV Telemetry Dashboard link'],
    status: 'UPCOMING',
  },
];

export const mockEmployeePulse: import('./types').EmployeePulseData = {
  pulseScore: 92,
  organizationSentiment: 'VERY_POSITIVE',
  surveyParticipationPercent: 94.5,
  feedbackSubmittedCount: 28,
  suggestionsCount: 14,
  recognitionEventsCount: 12,
};

export const mockBoardInvestorReports: import('./types').BoardInvestorReport[] = [
  {
    id: 'doc_01',
    documentTitle: 'InnoVibe Q2 2026 Executive Financial & Operations Audit',
    type: 'BOARD_REPORT',
    fileSize: '4.8 MB PDF',
    uploadedAt: 'Today at 07:00 AM',
    accessLevel: 'RESTRICTED_BOARD',
    downloadCount: 6,
  },
  {
    id: 'doc_02',
    documentTitle: 'Series-B Growth Pitch Deck & Coastal Hub Expansion Model',
    type: 'INVESTOR_UPDATE',
    fileSize: '12.2 MB PDF',
    uploadedAt: '22 Jun 2026',
    accessLevel: 'INVESTORS_ONLY',
    downloadCount: 14,
  },
  {
    id: 'doc_03',
    documentTitle: 'Annual General Meeting (AGM) Governance & Compliance Filing 2026',
    type: 'AGM_DOC',
    fileSize: '2.4 MB PDF',
    uploadedAt: '15 Jun 2026',
    accessLevel: 'PUBLIC_AGM',
    downloadCount: 42,
  },
];

export const mockMediaPrItems: import('./types').MediaPrItem[] = [
  {
    id: 'pr_01',
    headline: 'InnoVibe Sets New Benchmark for Connected EV Fleet Reliability in Andhra Pradesh',
    outletName: 'The Hindu Tech & Business',
    mediaType: 'NEWS_COVERAGE',
    publishedDate: '23 Jun 2026',
    sentiment: 'POSITIVE',
    reachCount: '450k Readers',
  },
  {
    id: 'pr_02',
    headline: 'InnoVibe CEO Sri Hari Kolusu Discusses Zero Back-Office Autonomous EV Servicing',
    outletName: 'EV India Magazine',
    mediaType: 'INTERVIEW',
    publishedDate: '20 Jun 2026',
    sentiment: 'POSITIVE',
    reachCount: '180k Views',
  },
  {
    id: 'pr_03',
    headline: 'Official Press Release: InnoVibe Expands Coastal Hub Grid to 5 AP Cities',
    outletName: 'PR Newswire India',
    mediaType: 'PRESS_RELEASE',
    publishedDate: '18 Jun 2026',
    sentiment: 'POSITIVE',
    reachCount: '620k Impressions',
  },
];

export const mockAiCommDraftTemplates: import('./types').AiCommDraft[] = [
  {
    id: 'draft_01',
    type: 'ANNOUNCEMENT',
    title: 'Company-Wide Celebration: Milestone Revenue & Fleet Reliability',
    generatedText: 'Team InnoVibe, I am proud to announce that through your dedication, we achieved ₹12.45L in monthly revenue and maintained 94.2% average battery SOH across all 148 connected EVs. Thank you for your relentless commitment to zero-downtime EV mobility.',
    tone: 'INSPIRATIONAL',
  },
  {
    id: 'draft_02',
    type: 'SPEECH',
    title: 'Opening Remarks for Board of Directors Strategic Review',
    generatedText: 'Members of the Board, welcome to our Q2 2026 review. Over the past 90 days, InnoVibe has demonstrated that software-driven BMS diagnostics and automated dispatch unlock 30.8% operating margins while scaling our coastline footprint to 5 active hub cities.',
    tone: 'REASSURING',
  },
];

// Module 10: Reports & Analytics Mock Data
export const mockReportLibraryCards: import('./types').ReportCardItem[] = [
  {
    id: 'rpt_01',
    reportTitle: 'Q2 Executive Revenue & Profitability Analysis Report',
    category: 'BUSINESS',
    frequency: 'QUARTERLY',
    lastGenerated: 'Today, 06:00 AM',
    fileFormat: 'PDF',
    summarySnippet: 'Detailed analysis of gross revenue (₹12.45L), net operating margins (30.8%), and coastal hub revenue contributions.',
    size: '3.4 MB',
    isPopular: true,
  },
  {
    id: 'rpt_02',
    reportTitle: 'Connected EV Fleet Health & Battery Degradation Audit',
    category: 'FLEET',
    frequency: 'MONTHLY',
    lastGenerated: 'Yesterday',
    fileFormat: 'EXCEL',
    summarySnippet: 'IoT telemetry audit of 148 connected EVs, BMS cell health, fast-charge cycle ratios, and predicted pack replacements.',
    size: '8.2 MB',
    isPopular: true,
  },
  {
    id: 'rpt_03',
    reportTitle: 'Coastal Hub Operations & Service SLA Compliance Report',
    category: 'OPERATIONS',
    frequency: 'WEEKLY',
    lastGenerated: '23 Jun 2026',
    fileFormat: 'PDF',
    summarySnippet: 'Branch SLA compliance breakdown across Kakinada (98%), Vijayawada (94%), Rajahmundry (95%), Vizag (93%), and Guntur (88%).',
    size: '2.1 MB',
  },
  {
    id: 'rpt_04',
    reportTitle: 'Workforce Productivity & EV Technician Competency Review',
    category: 'HR',
    frequency: 'MONTHLY',
    lastGenerated: '20 Jun 2026',
    fileFormat: 'PDF',
    summarySnippet: 'Technician output per bay, EV safety certifications, attendance rates, and hiring pipeline metrics.',
    size: '1.8 MB',
  },
  {
    id: 'rpt_05',
    reportTitle: 'Customer Retention, CSAT & Doorstep Feedback Summary',
    category: 'CUSTOMER',
    frequency: 'MONTHLY',
    lastGenerated: '18 Jun 2026',
    fileFormat: 'PDF',
    summarySnippet: '98.2% customer satisfaction score, 1-click doorstep feedback metrics, and recurring AMC renewal analysis.',
    size: '2.5 MB',
  },
  {
    id: 'rpt_06',
    reportTitle: 'CapEx Budget Utilization & Vendor Cash Flow Breakdown',
    category: 'FINANCE',
    frequency: 'MONTHLY',
    lastGenerated: '15 Jun 2026',
    fileFormat: 'EXCEL',
    summarySnippet: 'CapEx spend against approved ₹1.82Cr budget, LFP battery module procurement ledger, and vendor payment cycles.',
    size: '4.6 MB',
  },
];

export const mockKpiVariances: import('./types').KpiVarianceItem[] = [
  {
    id: 'var_01',
    kpiName: 'Monthly Gross Revenue',
    category: 'Finance',
    quarterlyGoal: '₹12.00 Lakhs',
    actualAchievement: '₹12.45 Lakhs',
    forecastValue: '₹13.80 Lakhs',
    variancePercent: 3.75,
    status: 'EXCEEDING',
  },
  {
    id: 'var_02',
    kpiName: 'Fleet Average Battery SOH',
    category: 'Fleet',
    quarterlyGoal: '92.0%',
    actualAchievement: '94.2%',
    forecastValue: '93.5%',
    variancePercent: 2.39,
    status: 'EXCEEDING',
  },
  {
    id: 'var_03',
    kpiName: 'Same-Day Service SLA Compliance',
    category: 'Operations',
    quarterlyGoal: '95.0%',
    actualAchievement: '94.8%',
    forecastValue: '96.2%',
    variancePercent: -0.21,
    status: 'TARGET_MET',
  },
  {
    id: 'var_04',
    kpiName: 'Customer CSAT Score',
    category: 'Customer',
    quarterlyGoal: '95.0%',
    actualAchievement: '98.2%',
    forecastValue: '98.5%',
    variancePercent: 3.37,
    status: 'EXCEEDING',
  },
  {
    id: 'var_05',
    kpiName: 'Guntur Hub SLA Compliance',
    category: 'Operations',
    quarterlyGoal: '95.0%',
    actualAchievement: '88.5%',
    forecastValue: '94.0%',
    variancePercent: -6.84,
    status: 'ATTENTION',
  },
];

export const mockScheduledReports: import('./types').ScheduledReportItem[] = [
  {
    id: 'sch_01',
    title: 'Daily Executive Morning Briefing',
    recipients: 'Sri Hari Kolusu (CEO)',
    scheduleCron: 'Every Day at 07:30 AM',
    deliveryChannels: ['EMAIL', 'PDF', 'DASHBOARD_LINK'],
    status: 'ACTIVE',
  },
  {
    id: 'sch_02',
    title: 'Weekly Coastal Hub Operations & SLA Report',
    recipients: 'CEO, COO, Branch Managers',
    scheduleCron: 'Every Monday at 08:00 AM',
    deliveryChannels: ['EMAIL', 'EXCEL'],
    status: 'ACTIVE',
  },
  {
    id: 'sch_03',
    title: 'Monthly Financial Audit & CapEx Ledger',
    recipients: 'CEO, CFO, Board Audit Committee',
    scheduleCron: '1st of every month at 09:00 AM',
    deliveryChannels: ['EMAIL', 'PDF', 'EXCEL'],
    status: 'ACTIVE',
  },
  {
    id: 'sch_04',
    title: 'Quarterly Board Presentation Pack',
    recipients: 'CEO, Board Members (5)',
    scheduleCron: 'End of Quarter (Mar, Jun, Sep, Dec)',
    deliveryChannels: ['EMAIL', 'PDF'],
    status: 'ACTIVE',
  },
];

export const mockPredictiveAnalyticsModels: import('./types').PredictiveAnalyticsModel[] = [
  {
    id: 'pred_01',
    modelName: 'Q3 Revenue Trajectory Model',
    targetMetric: 'REVENUE',
    currentValue: '₹12.45L / mo',
    predictedValue: '₹15.80L / mo',
    timeframe: 'Next 90 Days',
    confidencePercent: 94,
    keyDriver: '+25 Euler EV fleets scaling in Kakinada & Vizag',
  },
  {
    id: 'pred_02',
    modelName: 'BMS Cell Replacement Demand',
    targetMetric: 'FLEET_GROWTH',
    currentValue: '12 Packs <80%',
    predictedValue: '18 Packs Needed',
    timeframe: 'Next 60 Days',
    confidencePercent: 92,
    keyDriver: 'High ambient temperature & 85k+ km vehicle mileage',
  },
  {
    id: 'pred_03',
    modelName: 'Doorstep EV Servicing Customer Demand',
    targetMetric: 'SERVICE_DEMAND',
    currentValue: '142 Requests / day',
    predictedValue: '210 Requests / day',
    timeframe: 'Next 30 Days',
    confidencePercent: 88,
    keyDriver: 'Launch of Visakhapatnam Port commercial AMC package',
  },
  {
    id: 'pred_04',
    modelName: 'EV Certified Mechanic Hiring Needs',
    targetMetric: 'HIRING_NEEDS',
    currentValue: '18 Mechanics',
    predictedValue: '24 Mechanics Needed',
    timeframe: 'Q3 2026',
    confidencePercent: 96,
    keyDriver: 'Opening of Guntur Bay 2 & Tirupati expansion',
  },
];

export const mockBoardPresentationSlides: import('./types').BoardPresentationSlide[] = [
  {
    id: 'sld_01',
    slideNumber: 1,
    title: 'Q2 Executive Summary & Coastal Growth Milestones',
    headlineMetric: '₹12.45L Monthly Revenue (+34% YoY)',
    executiveSummary: 'InnoVibe expanded its connected EV ecosystem across 5 coastal AP cities while maintaining 30.8% net operating margins and 94.2% fleet battery SOH.',
    keyPoints: [
      'Scaled active connected commercial EVs to 148 units.',
      'Achieved zero roadside breakdown incidents in June.',
      'Launched 1-click doorstep EV servicing in Vizag.',
    ],
    riskHighlights: ['Guntur hub technician capacity limit reached (88.5% SLA).'],
    recommendationText: 'Approve ₹60L CapEx allocation for 25 additional Euler EVs and fast-track 4 technician hires.',
  },
  {
    id: 'sld_02',
    slideNumber: 2,
    title: 'Financial Performance & Operating Margin Expansion',
    headlineMetric: '30.8% Net Margin (vs 24.2% Q1 Target)',
    executiveSummary: 'Software-led AMC subscriptions and predictive BMS diagnostics reduced emergency breakdown costs by 64%, unlocking 660 bps margin expansion.',
    keyPoints: [
      'Gross monthly revenue reached ₹12.45 Lakhs.',
      'Software AMC subscription revenue grew +42% MoM.',
      'CapEx payback cycle optimized to 11 months per EV.',
    ],
    riskHighlights: ['LFP cell raw material price fluctuations (+3.2%).'],
    recommendationText: 'Execute 12-month fixed price LFP cell supply contract with Exide/Amara Raja.',
  },
];

export const mockAiGeneratedReports: import('./types').AiGeneratedReport[] = [
  {
    id: 'air_01',
    title: 'Executive AI Brief: Q2 Coastal Operations & Business Health Audit',
    reportType: 'BUSINESS_HEALTH',
    executiveSummary: 'InnoVibe is operating at peak business health (93/100 Health Score). Fleet utilization is healthy at 93%, monthly revenue reached ₹12.45L (+3.7% above budget), and customer CSAT sits at 98.2%. The single operational bottleneck is Guntur bay SLA compliance (88.5%), which is being resolved via fast-track technician hiring.',
    keyInsights: [
      'Kakinada Hub generates 32% of company revenue with 98% SLA.',
      'Edge Middleware v2.4 reduced IoT latency by 45ms.',
      'Predictive BMS models correctly flagged 12 battery packs before failure.',
    ],
    recommendedActions: [
      'Approve ₹60L CapEx for 25 Euler EV units in Kakinada.',
      'Deploy 2 mobile service vans to Guntur immediately.',
      'Finalize Series-B pitch deck for July investor sync.',
    ],
    generatedAt: 'Today at 07:00 AM',
  },
];








